[package]
name = "multi-repo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "multi-repo"
path = "src/main.rs"

[dependencies]
base64.workspace = true
clap.workspace = true
multi-repo-core = { version = "0.1.0", path = "../multi-repo-core" }
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
